package helpers

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// getCallerDir attempts to find the directory of the original source file (e.g. main.go)
// by traversing the call stack and skipping known library paths.
// This provides an extremely robust anchor for 'go run' where os.Executable is in /tmp/.
func getCallerDir() string {
	for i := 1; i < 25; i++ {
		_, file, _, ok := runtime.Caller(i)
		if !ok {
			break
		}
		// Skip list: stdlib and platform internal libs
		skip := false
		libsToSkip := []string{
			"runtime/", "reflect/", "testing/",
			"distributed-config", "microservice-toolbox", "universal-logger",
			"flexible-logger", "safe-socket", "message-serializers",
			"<autogenerated>",
		}
		for _, lib := range libsToSkip {
			if strings.Contains(file, lib) {
				skip = true
				break
			}
		}

		if !skip && file != "" {
			return filepath.Dir(file)
		}
	}
	return ""
}

// -----------------------------------------------------------------------------
// GetLogPath returns the log file path based on the provided name.
// If name is empty, it falls back to the executable name.
func GetLogPath(name string) string {
	baseDir := "."
	exePath, err := os.Executable()
	if err == nil {
		exeDir := filepath.Dir(exePath)
		// If not in a temporary go-build directory, use the executable's directory
		if !strings.Contains(exeDir, "go-build") && !strings.Contains(exeDir, "T/go-build") {
			baseDir = exeDir
		} else {
			if callerDir := getCallerDir(); callerDir != "" {
				baseDir = callerDir
			} else if wd, err := os.Getwd(); err == nil {
				baseDir = wd
			}
		}
	} else {
		if callerDir := getCallerDir(); callerDir != "" {
			baseDir = callerDir
		} else if wd, err := os.Getwd(); err == nil {
			baseDir = wd
		}
	}

	logDir := filepath.Join(baseDir, "logs")

	// Ensure log directory exists
	_ = os.MkdirAll(logDir, 0755)

	if name != "" {
		// Clean the name to be safe for filenames
		name = strings.ReplaceAll(name, "/", "_")
		name = strings.ReplaceAll(name, "\\", "_")
		return filepath.Join(logDir, name+".log")
	}

	if err != nil {
		return filepath.Join(logDir, "application.log")
	}

	exeName := filepath.Base(exePath)
	ext := filepath.Ext(exeName)
	if ext != "" {
		exeName = strings.TrimSuffix(exeName, ext)
	}

	return filepath.Join(logDir, exeName+".log")
}
